import Provider from "@/Provider";
import Logo from "@/components/Logo";
import "@/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-100 h-screen`}>
        <Provider>
          <header className="bg-transparent">
            <div className="container">
              <div className="py-4 px-3 text-center ">
                <Logo />
              </div>
            </div>
          </header>
          <main className="w-full h-auto">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
